# Generated by Django 4.2.13 on 2024-05-08 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
