# Generated by Django 4.2.13 on 2024-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_productincart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincart',
            options={'verbose_name_plural': 'Products in cart'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(related_name='order', to='storeapp.product', verbose_name='Заказ')),
            ],
        ),
    ]
